### ISSUE TITLE
[📌 To Do] 1/5 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#100]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작
- [ ] 프로젝트 생성
- [ ] 프레임워크 및 기초 깃허브 저장소 골격 제작 (위키, 리드미 등)

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 모던 자바스크립트 튜토리얼 복습 [레퍼런스](https://ko.javascript.info/)
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] 타입스크립트 복습 [레퍼런스](https://www.udemy.com/course/understanding-typescript/learn/lecture/16935762#overview)
- [ ] 타입스크립트 챌린지 [레퍼런스](https://github.com/type-challenges/type-challenges)
- [ ] React Native 강좌 듣기 및 클론코딩

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리 
- [ ] 타입스크립트 공부내용 깃프로젝트 정리
