### ISSUE TITLE
[📌 To Do] 1/3 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#103]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드
  - [ ] 홈 메인 레이아웃 제작 및 회원가입, 로그인 페이지 구축
  - [ ] 무한스크롤 구조 도입 탐색 및 테스트
  
- ### 백엔드
  - [ ] 인증시스템 관련 DB 다이어그램 구축
  - [ ] 인증시스템 관련 깃북 구축
  - [ ] express 서버 및 인증시스템 구축 및 메일인증 시스템 도입 탐색 및 테스트

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] React native 강좌 시청 및 클론코딩 진행 [레퍼런스](https://www.udemy.com/course/react-native-the-practical-guide/learn/lecture/15419940?start=30#overview)
- [ ] 타입스크립트 복습 [레퍼런스](https://www.udemy.com/course/understanding-typescript/learn/lecture/16935762#overview)
- [ ] 타입스크립트 챌린지 [레퍼런스](https://github.com/type-challenges/type-challenges)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리 
- [ ] 타입스크립트 공부내용 깃프로젝트 정리
- [ ] 개인프로젝트 dev로그, (optional) 에러로그 작성
