### ISSUE TITLE
[📌 To Do] 1/10 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#107]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드
  - [ ] 메인페이지 반응형 레이아웃 제작
  - [ ] 회원인증 페이지 반응형 레이아웃 제작 ( 회원가입, 로그인, 로그아웃 )
  - [ ] 회원수정 페이지 반응형 레이아웃 제작 
   
- ### 백엔드
  - [ ] 일반 회원가입 라우팅 처리 
  - [ ] 카카오 Oauth 추가
  - [ ] 구글 Oauth 추가

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
