### ISSUE TITLE
[📌 To Do] 1/11 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#110]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드
  - [ ] 메인페이지 포스팅 컴포넌트 제작
  - [ ] 포스팅 컴포넌트 메인메뉴 제작
  - [ ] 반응형 레이아웃 체크
  - [ ] 일정 이상 스크롤이 실행되었을 때 로그인이 되어있지 않다면 로그인을 요청하는 모달 팝업
      
- ### 백엔드
  - [ ] 일반 로그인 관련 라우팅 처리
  - [ ] 메일인증 추가 내용 검토 및 테스트

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
