### ISSUE TITLE
[📌 To Do] 1/12 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#112]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드
  - [ ] 로그인, 회원가입 모달 제작 완성
  - [ ] 로그인, 회원가입, Oauth제작 완성 ( 목표 = javascript를 이용한 팝업형 Oauth 탐색 )
  - [ ] 메일인증 구현 (목표 = 일반회원가입시 메일인증 요청 과정 추가 )

      
- ### 백엔드
  - [ ] 로그인, 회원가입 라우팅 처리 제작
  - [ ] 메일인증 구현 (목표 = node mailer을 이용한 응답처리)
  - [ ] 

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
