### ISSUE TITLE
[📌 To Do] 1/10 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#116]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드
  - [ ] 네이버 Oauth 로그인 구현
  - [ ] 메일 인증 페이지 구현

      
- ### 백엔드
  - [ ] 로그인, 회원가입 라우팅 처리 제작
  - [ ] 메일인증 로직 구현 (회원가입, 비밀번호찾기)

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
