### ISSUE TITLE
[📌 To Do] 1/17 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#118]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드
  - [ ] Oauth 모달아이콘 반응형 제작 완료
  - [ ] Redux persist 구조 제작
  - [ ] Oauth 가입성공 완료 시 redux에 상태저장 (loginstate)
  - [ ] 일반 로그인 계속하기 눌렀을 때 메일인증 모달로 컨텐츠 변경 구현
  - [ ] 메일인증 내부 카운팅하는 시간 컴포넌트 제작
      
- ### 백엔드
  - [ ] Oauth 정보가 전달되었을 때 해당정보 데이터베이스 저장 후, accessToken "body"로 전달
        (react native 대응 위함. 나중, refresh는 유저에 저장)
  - [ ] 메일 인증 관련 로직 구현
  - [ ] 일반 로그인 완료 후 응답 라우팅 제작

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
