### ISSUE TITLE
[📌 To Do] 1/18 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#120]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] 회원가입 버튼 눌렀을 때 기존에 유저가 존재한다면 에러응답 (계속되는 버튼 클릭을 방지위해 abort 도입 시도)
  - [ ] 메일 인증코드 실패 5회 누적되면 redux 상태에 저장 ( expire저장. 만약 expire 이내면하면 코드인증 칸 disable. 넘으면 expire 삭제. ref이용)
  - [ ] 메일 인증코드 성공시 회원정보 저장 후, jwt 제작하여 전달. (성공요청 받으면 곧바로 모달창 닫히고 헤더 변경)
  - [ ] Oauth버튼 눌러서 성공시 얻어오는 데이터 서버 전달 후, 해당 내용 저장 (성공요청 받으면 곧바로 모달창 닫히고 헤더 변경 )
  - [ ] 로그인 요청시 유저가 없거나 비밀번호가 틀렸으면 비밀번호를 다시 확인해달라는 문구 띄우기 (및 계속 버튼클릭을 방지하기 위해 abort 도입 시도)
  - [ ] 로그인 성공시 jwt 제작 후 성공요청과 함께 전달
      
## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
