### ISSUE TITLE
[📌 To Do] 1/21 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#126]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] Next.js로 기존 프로젝트 전환 완료
  - [ ] Next.js 강좌 수강 

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
- [ ] Next.js 강좌 내용 깃프로젝트, 벨로그 정리
