### ISSUE TITLE
[📌 To Do] 1/31 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#146]
# ✔️ 해야 할 일 리스트

## 제출용 프로젝트 제작
- 프론트엔드
  - [ ] 헤더와 메인페이지 css 분리 구현(반응형)
  - [ ] 로그인 모달, 회원가입 모달 구현
  - [ ] 프로필 이미지, 닉네임 클릭시 변경창 구현
  - [ ] 새로운 포스트카드 등록 구현 ( 텍스트창 div 안에서 해시태그 파트 구현 가능한지)

- 백엔드
  - [ ] 서버 및 DB 선택 ( Lamda vs Express, firebase vs mogoDB)
  - [ ] 간단한 회원가입, 로그인 기능 구현
  - [ ] JWT 토큰으로 인증상태 유지 구현

## 개인공부
- [ ] 모던 자바스크립트 deep dive 3장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
