### ISSUE TITLE
[📌 To Do] 2/2 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#149]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] 로그인 및 메일인증 기능 구현
  - [ ] 게스트로 시작하기 기능 구현
  - [ ] ContextAPI => Redux로 메인기능 이식 및 redux persist로 유지해야 할 내용 저장
  - [ ] Click to Edit 파트 구현 ( 이미지 변경, 닉네임 변경 )
  - [ ] 임시 게시물 데이터 저장

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
- [ ] Next.js 공부내용 깃프로젝트, 벨로그 정리
