### ISSUE TITLE
[📌 To Do] 2/3~2/4 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#151]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] 메일인증 구현 완료
  - [ ] 첫 로딩 와이어프레임 제작 ("/" 경로)
  - [ ] DB 테이블 제작 
    ( category 테이블 => 각 카테고리는 N개의 Document가 있음
    ( document테이블 => 각 document에는 게시자 정보, 내용, 쓴 날짜, 이미지 등 + 카테고리아이디)

  - [ ] 첫 로딩시 대표 게시판 게시글 개수 확인 후 개시글 있으면 최초 5개만 전달
  - [ ] 검색바 자동완성 기능
    ( tag 테이블 => 미리 일부 태그들을 저장해두고, input창에 입력이 일어날 때 해당 태그들 내용을 추천함.)
    ( 태그의 컬럼으로는 해당 태그가 들어간 게시글의 갯수가 들어가야 함 )
    ( 미리 앱이 실행되었을 때, 비동기적으로 갯수가 많은 상위티어 리스트를 받아놓은 후, 처음에는 거기서 확인하고 내용에 없다면 서버요청해서 확인해서 
      나타내도록 한다)
 
## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
- [ ] Next.js 공부내용 깃프로젝트, 벨로그 정리
