### ISSUE TITLE
[📌 To Do] 2/8 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#156]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] 제출용 프로젝트 aws 배포 후 READ.ME 수정
  - [ ] 원티드 이력서 및 기업 쇼트 에세이 작성
  - [ ] (optional) 리드미 배포링크 첨부 수정 및 테스트 브렌치 제작 후 게시글 작성 페이지 구현
  
## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
