### ISSUE TITLE
[📌 To Do] 2/9 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#157]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] 샘플용 필터링 input 랜더파트 구현
  - [ ] aws 배포 및 버그 발견시 수정
  - [ ] 각 보딩 페이지 메인 프레임 구현
  - [ ] 게시글 작성 파트 구현 ( 1차목표 : 직접구현, 2차목표 : library )

## 개인공부
- [ ] 모던 자바스크립트 deep dive 7장 복습
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
- [ ] Next.js 공부내용 깃프로젝트, 벨로그 정리
