### ISSUE TITLE
[📌 To Do] 2/11 ~ 2/12 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#160]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] 토큰인증 바디나 헤더로 전송 후, 프론트에서 env의 해시값으로 암호화한뒤 로컬스토리지 저장 ( 인증요청 필요한 서비스는 헤더에 내용전달 )
  - [ ] 게시판 와이어프레임 제작
  - [ ] 서버 테이블 및 임시 데이터 저장
  - [ ] 게시글 클릭시 게시글 상세내용
  - [ ] 게시글 댓글달기 기능 구현 및 (작성자면) 댓글 삭제기능 구현
  - [ ] 게시글  작성 및 (작성자면) 게시글 삭제기능

## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습 (워밍업)
- [ ] 아침 프론트엔드 면접지식 영상 시청
- [ ] 기술면접 준비 ( 1. 새로운 개념으로 블로깅 주제를 찾고 작성, 2. 빠르게 복습 및 새로운 지식 습득 )
- [ ] typescript 학습
          [기본개념 정리본](https://heropy.blog/2020/01/27/typescript/)
          [타입스크립트 한글문서](https://typescript-kr.github.io/)
          [타입스크립트 챌린지](https://github.com/type-challenges/type-challenges)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
- [ ] typescript 학습 내용 정리
