### ISSUE TITLE
[📌 To Do] 2/15 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#164]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] Next.js data fetching toy 제작
  - [ ] Next.js 클론코딩 (block chain clone)[레퍼런스](https://www.youtube.com/watch?v=frCsGK4cKks)
  - [ ] 제작중인 프로젝트 Next.js로 이식

## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습 (워밍업)
- [ ] 아침 프론트엔드 면접지식 영상 시청
- [ ] 기술면접 준비 ( 1. 새로운 개념으로 블로깅 주제를 찾고 작성, 2. 빠르게 복습 및 새로운 지식 습득 )
- [ ] typescript 학습
          [기본개념 정리본](https://heropy.blog/2020/01/27/typescript/)
          [타입스크립트 한글문서](https://typescript-kr.github.io/)
          [타입스크립트 챌린지](https://github.com/type-challenges/type-challenges)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
- [ ] typescript 학습 내용 정리
