### ISSUE TITLE
[📌 To Do] 1/10 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#167]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] 게시판 보드 공지사항 레이아웃 완성
  - [ ] 게시판 보드 글 리스트 레이아웃 완성 (min height이 적용되어야 한다)
  - [ ] 게시판 보드 페이지네이션 레이아웃 완성 (들어오는 데이터를 최대 n개까지 가져와서 갯수를 나눠 분배하고 페이징. 이때 데이터를 이미 배열 형태로 쪼개서 나누고 있어야 함. 그 이후 요청시 서버에 페이지 값을 제공하고 mysql로 해당 페이지 offset만큼 넘어가서 그 이후로 n개만큼 조회하도록 만들어야 함.
  - [ ] 사이드바 광고 임시 레이아웃 작성 ( 기사 링크, 일반 광고가 들어올 것임 )

## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습 (워밍업)
- [ ] 아침 프론트엔드 면접지식 영상 시청
- [ ] 기술면접 준비 ( 1. 새로운 개념으로 블로깅 주제를 찾고 작성, 2. 빠르게 복습 및 새로운 지식 습득 )
- [ ] typescript 학습
          [기본개념 정리본](https://heropy.blog/2020/01/27/typescript/)
          [타입스크립트 한글문서](https://typescript-kr.github.io/)
          [타입스크립트 챌린지](https://github.com/type-challenges/type-challenges)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
- [ ] typescript 학습 내용 정리
