### ISSUE TITLE
[📌 To Do] 3/10 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#178]
# ✔️ 해야 할 일 리스트

- ### 프론트엔드
  - [ ] 프리온보딩 기업과제 ( vue, pentagon graph) 완료

## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습 (워밍업)
- [ ] [모던 자바스크립트 튜토리얼 2단원 학습](https://ko.javascript.info/)
- [ ] 기술면접 준비 ( option 1. 새로운 개념으로 블로깅 주제를 찾고 작성, option 2. 빠르게 복습 및 내용 정리 ) 

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
