### ISSUE TITLE
[📌 To Do] 3/14 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#198]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작

- ### 프론트엔드 && 백엔드
  - [ ] 기업과제 제작
 
## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습 (워밍업)
- [ ] [모던 자바스크립트 튜토리얼 2단원 학습](https://ko.javascript.info/)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
