### ISSUE TITLE
[📌 To Do] 3/10 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#210]
# ✔️ 해야 할 일 리스트

- ### 기업과제
  - [ ] 데이터 추가 로직 구현 ( 목표는 무한로딩 + 스크롤 with파악하여 포탈 )
  - [ ] url검색페이지 레이아웃 구현
  - [ ] 이미지 로딩시 스켈레톤 와이어프레임 구현 

## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습 (워밍업)
- [ ] [모던 자바스크립트 튜토리얼 2단원 학습](https://ko.javascript.info/)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
