### ISSUE TITLE
[📌 To Do] 3/29 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#214]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작
- [ ] 커미션 사이트 기초 설계 작성 (종이에 아이디어 러프설정)

> 0. 제작이유 : 커미션 보통 카카오 채팅 + 입금식 => 작가가 안만들고 잠수타도 보호방법 없음.
> 1. next.js 기반 or React 기반, 트위터 레이아웃 +  페이지네이션, 스켈레톤, 커미션 시스템 (네이버 안심거래 시스템처럼 하면 좋을듯)
> 2. 커미션 시스템은 해외결제도 예상해서 paypal로 구현, 차후 추가
> 3. 단계별 설정 ( a. 초기러프단계-결제는 옵션, 결제시 작가에게 입금/ b. 실제 결제단계-다 완성되었을 때 상호 완료시 제공)

- [ ] firebase 및 mongoDB와 연동테스트 (mongoDB는 이미지저장소로 사용가능한지 확인)

## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습 (워밍업)
- [ ] [모던 자바스크립트 튜토리얼 2단원 학습](https://ko.javascript.info/)
- [ ] 기술면접 준비 ( option 1. 새로운 개념으로 블로깅 주제를 찾고 작성, option 2. 빠르게 복습 및 내용 정리 ) 
- [ ] typescript 학습
          [기본개념 정리본](https://heropy.blog/2020/01/27/typescript/)
          [타입스크립트 한글문서](https://typescript-kr.github.io/)
          [타입스크립트 챌린지](https://github.com/type-challenges/type-challenges)
- [ ] CSS 디자인 참조공부 (30분)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
- [ ] typescript 학습 내용 정리
