### ISSUE TITLE
[📌 To Do] 4/1 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#216]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작
- [ ] 

## 개인공부
- [ ] 모던 자바스크립트 deep dive 5장 복습 (30분, 시작시간 8시 30분)
- [ ] 기술면접 준비 ( 2시간, 블로깅까지, 여기까지 11시) 
- [ ] 코딩테스트 ( 식사 후 오후 2시 30분까지 )
- [ ] 개인 프로젝트 제작 ( 최소 7시까지 )

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리
