### ISSUE TITLE
[📌 To Do] 4/12 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#225]
- [ ] 9:00 ~ 9:30 모던 자바스크립트 복습
- [ ] 9:30 ~ 10:30 면접내용 준비
- [ ] 11:00 ~ 12:00 블로깅

- [ ] ~ 14:00 점심시간 포함 코딩테스트 
- [ ] 14:00 ~ 15:00 연습용 클론코딩
- [ ] 15:00 ~ 19:00 개인 프로젝트 제작
- [ ] 19:00 ~ 20:00 하루 회고 및 부족한 부분 보충
