### ISSUE TITLE
[📌 To Do] 12/22 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#61]
# ✔️ 해야 할 일 리스트

## 페어 인터뷰 준비
- [ ] 상대방이 준 문제 풀어보기
- [ ] 내가 준 문제 풀어보기
- [ ] 상대방이 준 공부주제
- [ ] 내가 준 공부주제

## 개인공부

- [ ] 모던 자바스크립트 deep dive 5장 복습
- [ ] 모던 자바스크립트 튜토리얼 공부 (레퍼런스)[https://ko.javascript.info/]
- [ ] 타입스크립트 공부 [레퍼런스](https://heropy.blog/2020/01/27/typescript/)
- [ ] 타입스크립트 챌린지 [레퍼런스](https://github.com/type-challenges/type-challenges)
- [ ] css 공부 

- [ ] 모던 자바스크립트 공부내용 깃프로젝트 정리
- [ ] 타입스크립트 공부내용 깃프로젝트 정리
- [ ] css 공부내용 깃프로젝트 정리
- [ ] 페어 인터뷰 내용 깃프로젝트 정리
