### ISSUE TITLE
[📌 To Do] 12/23 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#63]
# ✔️ 해야 할 일 리스트

## 리스트
- [ ] 상대방이 내준 문제 풀이
- [ ] 내가 내준 문제 풀이
- [ ] 상대방이 내준 면접질문 정리
- [ ] 내가 내준 면접질문 정리

## 기록정리
- [ ] 면접질문 정리한 것 깃프로젝트로 기록
