### ISSUE TITLE
[📌 To Do] 12/1 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#65]
# ✔️ 해야 할 일 리스트

## 개인공부
- [ ] 과제형 면접 준비 ( 디자인 및 프론트엔드 데이터 전달 구조 구현 )
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] 모던 자바스크립트 deep dive 5장 복습
- [ ] 모던 자바스크립트 튜토리얼 복습 (레퍼런스)[https://ko.javascript.info/]
- [ ] 타입스크립트 복습 [레퍼런스](https://heropy.blog/2020/01/27/typescript/)
- [ ] 타입스크립트 챌린지 [레퍼런스](https://github.com/type-challenges/type-challenges)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트 정리 
- [ ] (optional) 과제형 공부내용 깃프로젝트 정리
- [ ] 모던 자바스크립트 공부내용 깃프로젝트 정리 
- [ ] 타입스크립트 공부내용 깃프로젝트 정리
