### ISSUE TITLE
[📌 To Do] 12/25 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#69]
# ✔️ 해야 할 일 리스트

## 개인공부
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] 모던 자바스크립트 deep dive 5장 복습
- [ ] 타입스크립트 챌린지 [레퍼런스](https://github.com/type-challenges/type-challenges)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트 정리 
- [ ] 모던 자바스크립트 공부내용 깃프로젝트 정리 
- [ ] 타입스크립트 공부내용 깃프로젝트 정리
