### ISSUE TITLE
[📌 To Do] 12/31 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#87]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작
- [ ] 아이디어 구상 및 프로젝트 필요사항 체크, 러프제작

## 개인공부
- [ ] responsive web 강좌 듣기
- [ ] react Native 클론코딩, 및 udemy 강좌 듣기
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] 모던 자바스크립트 deep dive 5장 복습
- [ ] 타입스크립트 복습 [레퍼런스](https://www.udemy.com/course/understanding-typescript/learn/lecture/16935762#overview)
- [ ] 타입스크립트 챌린지 [레퍼런스](https://github.com/type-challenges/type-challenges)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리 
- [ ] 타입스크립트 공부내용 깃프로젝트 정리
- [ ] 개인프로젝트 dev로그, (optional) 에러로그 작성
