### ISSUE TITLE
[📌 To Do] 1/2 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#91]
# ✔️ 해야 할 일 리스트

## 개인공부
- [ ] 타입스크립트 복습 [레퍼런스](https://www.udemy.com/course/understanding-typescript/learn/lecture/16935762#overview)
- [ ] 타입스크립트 챌린지 [레퍼런스](https://github.com/type-challenges/type-challenges)

## 기록정리
- [ ] 타입스크립트 공부내용 깃프로젝트 정리
