### ISSUE TITLE
[📌 To Do] 12/1 Todo

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#93]
# ✔️ 해야 할 일 리스트

## 개인 프로젝트 제작
- [ ] 프로젝트 생성
- [ ] 프레임워크 및 기초 깃허브 저장소 골격 제작 (위키, 리드미 등)
- [ ] 아이디어 조사
- [ ] 기술스텍 조사

## 개인공부
- [ ] 기술면접 준비 ( javascript, react, typescript, socketIO 등등...)
- [ ] 모던 자바스크립트 deep dive 5장 복습
- [ ] 모던 자바스크립트 튜토리얼 복습 [레퍼런스](https://ko.javascript.info/)
- [ ] 타입스크립트 복습 [레퍼런스](https://www.udemy.com/course/understanding-typescript/learn/lecture/16935762#overview)
- [ ] 타입스크립트 챌린지 [레퍼런스](https://github.com/type-challenges/type-challenges)

## 기록정리
- [ ] 기술면접 준비내용 깃프로젝트, 벨로그 정리 
- [ ] 모던 자바스크립트 공부내용 깃프로젝트 및 벨로그 정리
- [ ] 타입스크립트 공부내용 깃프로젝트 정리
- [ ] 개인프로젝트 dev로그, (optional) 에러로그 작성
